name: 'Terraform GCP VM'

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Set up Google Cloud SDK auth
      run: |
        echo "$GOOGLE_CREDENTIALS" > gcp-key.json

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var-file="terraform.tfvars"

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="terraform.tfvars"
